### ISSUE TITLE
ValueError: Cannot set verify_mode to CERT_NONE when check_hostname is enabled.

### ISSUE THREAD

**Issue by PrabeshGuragain** [PrabeshGuragain/prabesh#1]
import urllib.request,urllib.parse,urllib.error
from bs4 import BeautifulSoup
import ssl

ctx=ssl.create_default_context()
ctx.xheck_hostname=False
ctx.verify_mode = ssl.CERT_NONE

url=input('enter the name of url-')
html=urllib.request.urlopen(url,context=ctx).read()
soup=BeautifulSoup(html,'html.parser')

tags=soup('a')
for tag in tags:
    print(tag.get('href',None))

**Comment by PrabeshGuragain** [comment]
Traceback (most recent call last):
  File "C:/Users/pprab/OneDrive/Desktop/python files/Example_urllinks.py", line 7, in <module>
    ctx.verify_mode = ssl.CERT_NONE
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\ssl.py", line 720, in verify_mode
    super(SSLContext, SSLContext).verify_mode.__set__(self, value)
ValueError: Cannot set verify_mode to CERT_NONE when check_hostname is enabled.
